-- Migration: Add User Authentication and Tracking
-- Description: Adds users table for authentication and adds user_email column to public_actions

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    blocked BOOLEAN DEFAULT FALSE,
    reset_token TEXT,
    reset_token_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add user_email column to public_actions table
ALTER TABLE public_actions ADD COLUMN IF NOT EXISTS user_email TEXT;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_blocked ON users(blocked);
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin);
CREATE INDEX IF NOT EXISTS idx_users_reset_token ON users(reset_token) WHERE reset_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_public_actions_user_email ON public_actions(user_email);

-- Enable Row Level Security (RLS) on users table
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- RLS Policies for users table (allow anon access for application usage)
CREATE POLICY "Enable read access for anon" ON users
    FOR SELECT
    TO anon
    USING (true);

CREATE POLICY "Enable insert access for anon" ON users
    FOR INSERT
    TO anon
    WITH CHECK (true);

CREATE POLICY "Enable update access for anon" ON users
    FOR UPDATE
    TO anon
    USING (true);

CREATE POLICY "Enable delete access for anon" ON users
    FOR DELETE
    TO anon
    USING (true);

-- Add updated_at trigger for users table
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
