-- Supabase Schema for PikPak Plus

-- Table: public_actions
-- Stores logs of actions performed by the server (e.g., adding tasks)

create table if not exists public_actions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    action text not null,
    data jsonb default '{}'::jsonb
);

-- Enable Row Level Security (RLS)
alter table public_actions enable row level security;

-- Policy: Allow read access (SELECT) for anon key
create policy "Enable read access for anon" on public_actions
    for select
    to anon
    using (true);

-- Policy: Allow write access (INSERT) for anon key
create policy "Enable insert access for anon" on public_actions
    for insert
    to anon
    with check (true);

-- Policy: Allow update access (UPDATE) for anon key (optional, if needed)
create policy "Enable update access for anon" on public_actions
    for update
    to anon
    using (true);
