-- Supabase Schema for PikPak Plus

-- Table: public_actions
-- Stores logs of actions performed by the server (e.g., adding tasks)

create table if not exists public_actions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    action text not null,
    data jsonb default '{}'::jsonb
);

-- Enable Row Level Security (RLS)
alter table public_actions enable row level security;

-- Policy: Allow read access (SELECT) for anon key
create policy "Enable read access for anon" on public_actions
    for select
    to anon
    using (true);

-- Policy: Allow write access (INSERT) for anon key
create policy "Enable insert access for anon" on public_actions
    for insert
    to anon
    with check (true);

-- Policy: Allow update access (UPDATE) for anon key (optional, if needed)
create policy "Enable update access for anon" on public_actions
    for update
    to anon
    using (true);

-- Table: daily_statistics
-- Stores daily aggregated statistics
create table if not exists daily_statistics (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    date date not null unique,
    tasks_added integer default 0,
    storage_used bigint default 0,
    transfer_used bigint default 0,
    downstream_traffic bigint default 0,
    premium_expiration timestamp with time zone
);

-- Enable RLS for daily_statistics
alter table daily_statistics enable row level security;

-- Policies for daily_statistics
create policy "Enable read access for anon" on daily_statistics
    for select
    to anon
    using (true);

create policy "Enable insert access for anon" on daily_statistics
    for insert
    to anon
    with check (true);

create policy "Enable update access for anon" on daily_statistics
    for update
    to anon
    using (true);

-- Indexes for performance optimization
CREATE INDEX IF NOT EXISTS idx_daily_statistics_date ON daily_statistics(date DESC);
CREATE INDEX IF NOT EXISTS idx_public_actions_created_at ON public_actions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_public_actions_action_created ON public_actions(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_public_actions_magnet_hash ON public_actions((data->>'info_hash')) WHERE action = 'add';
CREATE INDEX IF NOT EXISTS idx_public_actions_url ON public_actions((data->>'url')) WHERE action = 'add';
CREATE INDEX IF NOT EXISTS idx_public_actions_file_id ON public_actions((data->>'file_id')) WHERE action = 'share';


-- Table for storing PikPak tokens (Singleton row)
CREATE TABLE IF NOT EXISTS pikpak_tokens (
    id INTEGER PRIMARY KEY DEFAULT 1,
    username TEXT,
    password TEXT,
    access_token TEXT,
    refresh_token TEXT,
    access_token_expires_at TIMESTAMP WITH TIME ZONE,
    refresh_token_expires_at TIMESTAMP WITH TIME ZONE,
    user_id TEXT,
    captcha_token TEXT,
    captcha_expires_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Enable RLS (Row Level Security) - Optional but good practice
ALTER TABLE pikpak_tokens ENABLE ROW LEVEL SECURITY;

-- Allow all access for now (since we use service key)
CREATE POLICY "Allow all access" ON pikpak_tokens FOR ALL USING (true) WITH CHECK (true);

